### PR TITLE
Use NuGet in Linux and Windows

### PR DESCRIPTION
**Pull request by msoucy**
Based on code from:
https://peteris.rocks/blog/cross-platform-builds-on-windows-and-mono-with-msbuild/

This should solve part of the issues with Linux builds - robotdotnet/WPILib#101 will probably handle most of the remaining issues.

### CODE REVIEW

**Comment by ThadHouse** [comment]
Cool. I didn't know if the targets file would accept full msbuild commands. 

There are still a few issues, that I don't know what the solution is. NuGet on linux is not looking at the NuGet.config, so it won't build the current master. And Sandcastle is going to be another issue. And currently thats the only thing this repository is used for. But glad this fixes the basic build.

**Comment by msoucy** [comment]
Cool, one step closer to a functional Linux build at least!

**Comment by ThadHouse** [comment]
And the reason I never noticed the builds were not working is I had just install nuget from apt, so my linux systems and travis technically only need nuget to run. Didn't even need the mono command.

**Comment by msoucy** [comment]
Ah. I was relying on the NuGet.exe that's in the repository. I actually have minimal C# experience (I leave that to @mwoden) but I'm familiar with build systems.

NuGet appears to also be in Fedora's packages.

**Pull request merged**
